### PR TITLE
Document a one-liner to extract the Slack token

### PR DESCRIPTION
**Pull request by mootari**
Please feel free to edit the text to your liking! 🙏🏻 

Here is a more readable version of the snippet:
```js
JSON.parse(
  localStorage.localConfig_v2
).teams[
  // Conservative matching of the team ID
  document.location.pathname.match(/^\/client\/(T[A-Z0-9]+)/)[1]
].token
```

### CODE REVIEW

**Comment by jackellenberger** [comment]
Thank you so much, this is awesome! enjoy your cheese wedge 🧀 !

**Comment by mootari** [comment]
Hey, thanks for the kind words (and the cheese)! By the way, it looks like you're missing the closing `~`?

**Comment by mootari** [comment]
(You may also want to check out @rusq's [Playwright based solution](https://github.com/rusq/slackdump/blob/master/doc/login-auto.rst) to obtain both tokens.)

**Comment by jackellenberger** [comment]
> Hey, thanks for the kind words (and the cheese)! By the way, it looks like you're missing the closing `~`?

This is what I get for not waiting for reviews smh



> (You may also want to check out @rusq's [Playwright based solution](https://github.com/rusq/slackdump/blob/master/doc/login-auto.rst) to obtain both tokens.)

Ooo this is interesting! I'm generally of the mind to avoid headless browsers when i can, but it does seem like that's a much smoother way to go than using a chrom extension that is probably a security vulnerability waiting to happen. Created #73

**Pull request merged**
